name: Workflow Run B

on:
  workflow_dispatch:
  
concurrency: my-concurrency-group

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
    - uses: robherley/tmp-concurrency/.github/workflows/sleepy.yml
