# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: true
    steps:
    - run: sleep 60
  job-2:
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: true
    steps:
    - run: sleep 60
